### ISSUE TITLE
Test to upgrade to @sveltejs/kit@1.0.0-next.406 

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/sklein.xyz#10]
Test to upgrade to [@sveltejs/kit@1.0.0-next.406](https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%401.0.0-next.406) with https://github.com/sveltejs/kit/discussions/5774 https://github.com/sveltejs/kit/pull/5778 breaking changes.

**Comment by stephane-klein** [comment]
I have this error when I execute `pnpm run build`:

```
stephane@nuc-i7:~/git/github.com/stephane-klein/sklein.xyz (10-upgrade-svelte-kit-406) $ pnpm run build

> my-app@0.0.1 build /home/stephane/git/github.com/stephane-klein/sklein.xyz
> vite build

vite v3.0.7 building for production...
✓ 34 modules transformed.
.svelte-kit/output/client/_app/immutable/assets/avatar-fd7e3a86.webp                                    12.16 KiB
.svelte-kit/output/client/vite-manifest.json                                                            3.21 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_layout.svelte-64f09b99.js                    4.92 KiB / gzip: 2.17 KiB
.svelte-kit/output/client/_app/immutable/components/error.svelte-731fbb3f.js                            1.84 KiB / gzip: 0.83 KiB
.svelte-kit/output/client/_app/immutable/components/pages/garden/_page_slug_/_page.svelte-aed507cd.js   0.85 KiB / gzip: 0.53 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_page.svelte-97552a49.js                      5.60 KiB / gzip: 2.36 KiB
.svelte-kit/output/client/_app/immutable/chunks/0-322ed6ad.js                                           0.12 KiB / gzip: 0.12 KiB
.svelte-kit/output/client/_app/immutable/chunks/1-a8437820.js                                           0.11 KiB / gzip: 0.11 KiB
.svelte-kit/output/client/_app/immutable/start-15bca516.js                                              23.03 KiB / gzip: 8.80 KiB
.svelte-kit/output/client/_app/immutable/chunks/2-18178f5d.js                                           0.14 KiB / gzip: 0.13 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-36a7f5e5.js                                       8.07 KiB / gzip: 3.21 KiB
.svelte-kit/output/client/_app/immutable/chunks/3-97957e54.js                                           0.16 KiB / gzip: 0.14 KiB
.svelte-kit/output/client/_app/immutable/assets/+layout-e3f36674.css                                    1.41 KiB / gzip: 0.58 KiB
vite v3.0.7 building SSR bundle for production...
✓ 46 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/vite-manifest.json                                 1.81 KiB
.svelte-kit/output/server/index.js                                           74.84 KiB
.svelte-kit/output/server/entries/pages/_layout.svelte.js                    1.84 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js                  1.13 KiB
.svelte-kit/output/server/entries/pages/_page.svelte.js                      2.03 KiB
.svelte-kit/output/server/entries/pages/_page.server.js                      0.68 KiB
.svelte-kit/output/server/entries/pages/garden/_page_slug_/_page.svelte.js   0.48 KiB
.svelte-kit/output/server/entries/pages/garden/_page_slug_/_page.server.js   0.74 KiB
.svelte-kit/output/server/chunks/index.js                                    3.49 KiB
.svelte-kit/output/server/chunks/hooks.js                                    0.00 KiB
TypeError: glob.sync is not a function
    at load (file:///home/stephane/git/github.com/stephane-klein/sklein.xyz/.svelte-kit/output/server/entries/pages/_page.server.js:7:26)
    at load_server_data (file:///home/stephane/git/github.com/stephane-klein/sklein.xyz/.svelte-kit/output/server/index.js:1224:76)
    at file:///home/stephane/git/github.com/stephane-klein/sklein.xyz/.svelte-kit/output/server/index.js:1798:24
file:///home/stephane/git/github.com/stephane-klein/sklein.xyz/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.408_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:48
                                throw new Error(format_error(details, config));
                                      ^

Error: 500 /
    at file:///home/stephane/git/github.com/stephane-klein/sklein.xyz/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.408_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:48:11
    at save (file:///home/stephane/git/github.com/stephane-klein/sklein.xyz/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.408_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:336:4)
    at visit (file:///home/stephane/git/github.com/stephane-klein/sklein.xyz/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.408_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:223:3)
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///home/stephane/git/github.com/stephane-klein/sklein.xyz/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.408_svelte@3.49.0+vite@3.0.7/node_modules/@sveltejs/kit/src/vite/index.js:389:14)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by stephane-klein** [comment]
Error, fixed.
